config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :show, :create, :destroy] do
  end

  resources :posts do
    resources :comments, only: [:new, :create, :destroy]
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :posts, only: [:index] do
      resources :comments, only: [:create, :index]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.role == 'admin'
      can :manage, :all
    else
      can :manage, Post, author: user
      can :manage, Comment, author: user
      can :read, :all
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, foreign_key: 'post'

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/jwt_denylist.rb
class JwtDenylist < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Denylist

  self.table_name = 'jwt_denylist'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, foreign_key: 'post_id'

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: 'post_id'
  has_many :likes, foreign_key: 'post_id'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.limt(5).order(created_at: :desc)
  end

  private

  def update_post_counter
    user.increment!(:post_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher
  after_create :set_roles
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: self
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end

  private

  def set_roles
    update(role: 'user')
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  load_and_authorize_resource
  def index
    @comment = Comment.where({ post_id: params[:post_id] })
    render json: { success: true, message: 'Loaded all comments', data: { comment: @comment } }
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(text: comment_params[:text], user: current_user)

    if @comment.save
      render json: { success: true, data: { comment: @comment } }, status: :created
    else
      render json: { success: false, errors: @comment.errors }, status: :bad_request
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @posts = Post.all
    render json: { success: true, message: 'Loaded all posts', data: { posts: @posts } }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token
  load_and_authorize_resource
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    if @comment.save
      flash[:notice] = 'Comment successfully added!'
      redirect_to user_posts_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = 'Comment Deleted Succefully'
    redirect_back fallback_location: root_path
  end

  private

  def comment_params
    params.permit(:text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :verify_authenticity_token
  load_and_authorize_resource
  def index
    @user = User.includes(:posts).find(params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.includes(:comments, :likes).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    if current_user
      @post = current_user.posts.new(params[:id])
      @post.title = params[:title]
      @post.text = params[:text]
      if @post.save
        flash[:notice] = 'Post successfully added!'
        redirect_to user_posts_path
      else
        render 'new'
      end
    else
      redirect_to new_user_session_path, notice: 'You are not logged in.'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = 'Post Deleted Succefully'
    redirect_back fallback_location: root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if current_user
      @users = User.all
    else
      redirect_to user_session_path
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_new_comment.html.erb
<div class="container text-center">
  <form action="/users/<%=params[:user_id]%>/posts/<%=params[:id]%>/comments" method="POST">
    <%= csrf_meta_tags %>
    <div class="form-group  p-2">
      <label class="post-description">Write your comment</label><br>
      <textarea class="form-control" name="text"></textarea>
    </div>
    <div class="container">
      <div class="row">
        <div class="col text-center">
          <button class="btn btn-primary" type="submit">Submit</button>
        </div>
      </div>
    </div>
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogAppRail</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_comment_card.html.erb
<div class="container">
<div class="row m-4">
<div class="card bio">
<div class="card-body d-inline-flex">
  <p class="comment-author"><%= comment.author.name %></p>
  <p><%= comment.text %></p>
</div>
<div class="c-btn">
  <%if can? :destroy, comment%>
  <%= link_to user_post_path(comment.author_id, comment.post_id, comment.id), method: :delete do %>
    <button class="btn btn-primary comment-btn" >
    Delete
    </button>
  <%end%>
  <%end%>
</div>
</div>
</div>
</div>

app/views/posts/_post_card.html.erb
<div class="container">
  <div class="row m-4">
    <div class="card bio">
      <div class="card-body">
  <p class="card-title post-title"><%= post.title %>/p>
  <p class="card-text post-text"><%= post.text %></p>
<div class="post-info d-flex justify-content-end">
  <p class="m-2"> Comment: <%= post.comments_counter %> </p>
  <p class="m-2"> Likes: <%= post.likes_counter %> </p>
  <%= link_to user_post_path(post.author_id, post.id), method: :delete do %>
  <%if can? :destroy, post%>
    <button class="btn btn-primary post-btn" >Delete</button>
  <%end%>
  <%end%>
</div>
</div>
</div>
</div>
</div>

app/views/posts/index.html.erb
<%= render partial: "users/user_card", object: @user, as: 'user' %>
<% @user.posts.each do |post| %>
<a href="/users/<%= post.author_id %>/posts/<%= post.id %>" ><%= render partial: "post_card", object: post, as: 'post' %></a>
<% post.comments.each do |comment| %>
<%= render partial: "comment_card", object: comment, as: 'comment' %>
<% end %>
<% end %>
<div class="container">
<div class="row">
<div class="col text-center">
<button class="btn btn-primary"> Pagination </button>
</div>
</div>
</div>

app/views/posts/new.html.erb
<div class="container text-center">
  <form action="/users/<%=params[:user_id]%>/posts" method="POST">
    <%= csrf_meta_tags %>
    <div class="form-group p-2">
      <label class="post-title">Title</label><br>
      <input type="text" class="form-control" name="title"><br>
    </div>
    <div class="form-group  p-2">
      <label class="post-description">Write your post</label><br>
      <textarea class="form-control" name="text"></textarea>
    </div>
    <div class="container">
      <div class="row">
        <div class="col text-center">
          <button class="btn btn-primary" type="submit">Submit</button>
        </div>
      </div>
    </div>
  </form>
</div>

app/views/posts/show.html.erb
<%= render partial: "post_card", object: @post, as: 'post' %>
<% @post.comments.each do |comment| %>
<%= render partial: "comment_card", object: comment, as: 'comment' %>
<% end %>
<%= render partial: "comments/new_comment" %>

app/views/users/_user_card.html.erb
<div class="container">
<div class="row m-4" >
<% if user.photo %>
<div class="col-4">   
<img class="img-fluid user-img" src= <%= user.photo %> /> 
</div>
<% end %>
<div class="col-8">
<div class="card h-100">
<div class="card-body user-body">
<p class="card-title user-title"> <%= user.name %></p>
<p class="card-text user-text">Number of posts: <%= user.post_counter %> </p>
</div>
</div>
</div>
</div> 
</div>

app/views/users/index.html.erb
<%  @users.each  do |user| %>
<a href="/users/<%= user.id %>" class="link" >
<%= render partial: "user_card", object: user, as: 'user' %>
</a>
<% end %>

app/views/users/show.html.erb
<%= render partial: "user_card", object: @user, as: 'user' %>
<div class="container">
<div class="row m-4">
<div class="card bio">
<div class="card-body">
<p class="card-text"> <%= @user.bio %> </p>
</div>
</div>
</div>
</div>
<%  @user.posts.each  do |post| %>
<%= render partial: "posts/post_card", object: post, as: 'post' %>
<% end %>
<div class="container">
<div class="row">
<div class="col text-center">
<a href="<%= @user.id %>/posts" class="btn btn-primary">See all posts</a>
</div>
</div>
</div>